# Generated by Django 3.2.7 on 2021-11-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(default=1234567),
            preserve_default=False,
        ),
    ]
