# Generated by Django 3.2.7 on 2021-11-28 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 21, 7, 35, 689869, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=users.models.User.up_img),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.IntegerField(choices=[(1, '1')], default=1),
        ),
    ]
