# Generated by Django 3.2.7 on 2021-11-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211128_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='especialidade',
            field=models.CharField(choices=[('Oftamo', 'Oftamologista'), ('Urolo', 'Urologista'), ('Cardio', 'Cardiologista'), ('Pedia', 'Pediatra'), ('Enf', 'Enfermeiro(a)'), ('Aux', 'Auxiliar')], default='Aux', max_length=20),
        ),
    ]
