# Generated by Django 3.2.7 on 2021-11-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='especialidade',
            field=models.CharField(choices=[('Oftamo', 'Oftamologista'), ('Urolo', 'Urologista'), ('Cardio', 'Cardiologista'), ('Pedia', 'Pediatra'), ('Enf', 'Enfermeiro(a)'), ('Aux', 'Auxiliar'), ('Paciente', 'Paciente')], default='Paciente', max_length=20),
        ),
    ]
